# Llama Model Performance on MMLU (HELM) Example Card

title: "In-domain Model Consistency for Llama Family"

description: |
  Performance in a single domain benchmark should be consistent within a bound of variation for an entire model family

version: 1.0

organizations:
  - Kitware

submitter:
  name: Kitware TA2 Team
  email: aiq-ta2@kitware.com

tags:
  - example
  - llama
  - helm
  - mmlu

links:
  - title: "MAGNET"
    url: "https://github.com/AIQ-Kitware/aiq-magnet"
    type: "software"
  - title: "mmlu"
    url: "https://huggingface.co/datasets/cais/mmlu"
    type: "dataset"
  - title: "Precomputed HELM lite benchmark outputs"
    url: "https://console.cloud.google.com/storage/browser/crfm-helm-public/lite"
    type: "asset"

claim:
  python: |
     assert abs(comp_score - base_score) < threshold,f"{comp_model} score ({comp_score:.2f}) exceeds consistency bound on {base_model} ({base_score:.2f})"

pipeline:
  llama_predict:
    executable: 'python magnet/examples/llama_consistency/llama_predict.py'
    algo_params:
      helm_runs_path: './data/crfm-helm-public/lite/benchmark_output'           
      base_model:
          - meta/llama-2-13b
          - meta/llama-2-70b
          - meta/llama-2-7b
          - meta/llama-3-70b
          - meta/llama-3-8b
          - meta/llama-65b
      comp_model:
          - meta/llama-2-13b
          - meta/llama-2-70b
          - meta/llama-2-7b
          - meta/llama-3-70b
          - meta/llama-3-8b
          - meta/llama-65b
    out_paths:
      results_fpath: 'results.json'
    
symbols:
  threshold:
    type: float
    value: 0.1


